datasets:
  name: "bvcc"  # <- será usado para montar o path: embeddings/bvcc/{split}/metadata_with_embs.csv
  train:
    metadata_path: "embeddings/bvcc/train/metadata_with_embs.csv"
    target_column: "mos"
  val:
    metadata_path: "embeddings/bvcc/val/metadata_with_embs.csv"
    target_column: "mos"
  test:
    metadata_path: "embeddings/bvcc/test/metadata_with_embs.csv"
    target_column: "mos"