# configs/datasets/singmos.yaml
# Dataset configuration for SingMOS

datasets:
  name: "singmos"
  train:
    metadata_path: "/home/time_mos/casanova/Embeddings/datasets/Datasets_mos/singmos/DATA/sets/train_with_embs.csv"
    target_column: "mos"
  val:
    metadata_path: "/home/time_mos/casanova/Embeddings/datasets/Datasets_mos/singmos/DATA/sets/val_with_embs.csv"
    target_column: "mos"
  test:
    metadata_path: "/home/time_mos/casanova/Embeddings/datasets/Datasets_mos/singmos/DATA/sets/test_with_embs.csv"
    target_column: "mos"